# Numpy笔记(二)
## 1.3 numpy数组的操作
## 1.3.1 索引

In [1]:
import numpy as np

操作对象是一维numpy数组时, 索引和python中的列表的索引类似

In [8]:
# 向量的第二个元素
vec = np.array([1,2,3])
vec[1]

2

In [9]:
mtrx = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mtrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


当操作对象是二维numpy数组时, 需要提供行索引和列索引.

In [10]:
# 矩阵第二行第三列的元素
mtrx[1,2]

6

若只提供了行索引, 那么其将返回整行元素.

In [11]:
# 矩阵第二行所有元素
mtrx[1,]

array([4, 5, 6])

若想要返回整列元素, 则需要使用冒号. 

In [14]:
# 不可以直接省略行索引, 以下报错
mtrx[, 2]

SyntaxError: invalid syntax (<ipython-input-14-8366d833bf9d>, line 2)

In [15]:
# 想要返回整列元素, 则需要使用":"来填充行索引
# 矩阵第三列所有元素
mtrx[:, 2]

array([3, 6, 9])

In [16]:
# 刚才返回第二行所有元素我们是这样写的
mtrx[1,]

array([4, 5, 6])

In [17]:
# 完整写法为
mtrx[1,:]

array([4, 5, 6])

### 1.3.2 赋值

In [18]:
vec

array([1, 2, 3])

In [19]:
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# 一维numpy数组的赋值
vec[1] = 9
vec

array([1, 9, 3])

In [22]:
# 二维numpy数组的赋值
mtrx[1,1] = 99
mtrx

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [23]:
# 对整行赋值
mtrx[1,:] = [100, 101, 102]
mtrx

array([[  1,   2,   3],
       [100, 101, 102],
       [  7,   8,   9]])

In [24]:
# 对整列赋值
mtrx[:, 2] = [200, 201, 202]
mtrx

array([[  1,   2, 200],
       [100, 101, 201],
       [  7,   8, 202]])

In [26]:
# 可以将一行或一列的所有元素同时赋值为同一值
mtrx[1,:] = 99
mtrx

array([[  1,   2, 200],
       [ 99,  99,  99],
       [  7,   8, 202]])

### 1.3.3 切片

In [28]:
vec = np.array([1,2,3,4,5])

In [30]:
# 不包含索引'3'
vec[0:3]

array([1, 2, 3])

In [33]:
# ':'左边默认值为0
vec[:3]

array([1, 2, 3])

In [34]:
# ':'右边默认值为元素个数
vec[1:]

array([2, 3, 4, 5])

In [36]:
# 输出索引为0, 2, 4的元素
vec[0:5:2]

array([1, 3, 5])

In [37]:
# 第三个参数默认为1
vec[0:5:]

array([1, 2, 3, 4, 5])

In [44]:
# 最后一个元素, 负号表示倒数
vec[-1]

5

In [46]:
# 倒数第三个元素 - 倒数第一个元素
vec[-3:-1]

array([3, 4])

In [53]:
# 输出索引为: 4, 3, 2, 1, 0
vec[4::-1]

array([5, 4, 3, 2, 1])

In [55]:
# 输出元素为: 倒数第1个, 倒数第2个, 倒数第3个, 倒数第4个, 倒数第5个
vec[-1:-6:-1]

array([5, 4, 3, 2, 1])

In [56]:
# 可以直接省略前两个参数
vec[::-1]

array([5, 4, 3, 2, 1])

以上三种写法都可以表示一个一维numpy数组的逆序

对于二维的numpy数组, 原理是一样的.

In [66]:
mtrx = np.array([[1,2,3,4,5], [3,4,5,6,7], [5,6,7,8,9], [6,7,8,9,10], [7,8,9,10,11]])
mtrx

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

In [67]:
# 第一行到第三行, 第二列到第四列
mtrx[1:4,2:5]

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [68]:
mtrx[::2, ::2]

array([[ 1,  3,  5],
       [ 5,  7,  9],
       [ 7,  9, 11]])