# Numpy笔记(四)
## 1.5 线性代数

In [1]:
import numpy as np
from numpy import random

### 1.5.1 矩阵的转置
使用**T**属性来获取某一矩阵的转置

In [2]:
mat = random.randint(10, size=(3,2))
mat

array([[2, 4],
       [3, 1],
       [0, 1]])

In [3]:
mat.T

array([[2, 3, 0],
       [4, 1, 1]])

也可以使用transpose, 对于二维数组, 它的转置就相当于第一维和第二维互换.

In [4]:
mat.transpose((1,0))

array([[2, 3, 0],
       [4, 1, 1]])

transpose也可用于高维的numpy数组

In [5]:
mat = np.arange(16).reshape((2, 2, 4))
mat

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [6]:
# 前两个维度互换
mat.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [7]:
# 也可以使用swapaxes
mat.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

### 1.5.2 矩阵的乘法

In [8]:
m1 = random.randint(10, size=(3,2))
m1

array([[1, 8],
       [8, 7],
       [3, 6]])

In [9]:
m2 = random.randint(10, size=(2,3))
m2

array([[3, 3, 9],
       [8, 8, 6]])

In [10]:
m1.dot(m2)

array([[ 67,  67,  57],
       [ 80,  80, 114],
       [ 57,  57,  63]])

### 1.5.3 矩阵的逆
首先导入**numpy.linalg**.

In [11]:
import numpy.linalg as linalg

In [12]:
m3 = random.randint(10, size=(3,3))
m3

array([[8, 7, 9],
       [7, 9, 0],
       [1, 9, 6]])

In [13]:
linalg.inv(m3)

array([[ 0.08653846,  0.0625    , -0.12980769],
       [-0.06730769,  0.0625    ,  0.10096154],
       [ 0.08653846, -0.10416667,  0.03685897]])

### 1.5.4 QR分解

In [14]:
m3

array([[8, 7, 9],
       [7, 9, 0],
       [1, 9, 6]])

In [15]:
q, r = linalg.qr(m3)
q

array([[-0.74926865,  0.24168981,  0.61658943],
       [-0.65561007, -0.13902511, -0.74219098],
       [-0.09365858, -0.96034268,  0.26262143]])

In [16]:
r

array([[-10.67707825, -11.98829839,  -7.30536933],
       [  0.        ,  -8.20248144,  -3.58684782],
       [  0.        ,   0.        ,   7.12503345]])

In [17]:
q.dot(r)

array([[  8.00000000e+00,   7.00000000e+00,   9.00000000e+00],
       [  7.00000000e+00,   9.00000000e+00,  -8.88178420e-16],
       [  1.00000000e+00,   9.00000000e+00,   6.00000000e+00]])

### 1.5.5 矩阵的秩

In [18]:
linalg.det(m3)

623.99999999999955

### 1.5.6 特征值和特征向量

In [19]:
eigenvalues, eigenvectors = linalg.eig(m3)

In [20]:
eigenvalues

array([ 18.56170022+0.j        ,   2.21914989+5.35658322j,
         2.21914989-5.35658322j])

In [21]:
eigenvectors

array([[-0.72530181+0.j        , -0.61432591+0.j        , -0.61432591-0.j        ],
       [-0.53098429+0.j        ,  0.39049721+0.30847619j,
         0.39049721-0.30847619j],
       [-0.43817002+0.j        ,  0.09087173-0.60555791j,
         0.09087173+0.60555791j]])

$ Av=\lambda v,  Av- \lambda v=0$

In [22]:
m3.dot(eigenvectors) - eigenvalues * eigenvectors  

array([[ -1.06581410e-14 +0.00000000e+00j,
          4.66293670e-15 -4.44089210e-16j,
          4.66293670e-15 +4.44089210e-16j],
       [  0.00000000e+00 +0.00000000e+00j,
          5.55111512e-16 +8.88178420e-16j,
          5.55111512e-16 -8.88178420e-16j],
       [  0.00000000e+00 +0.00000000e+00j,
          3.10862447e-15 +0.00000000e+00j,
          3.10862447e-15 +0.00000000e+00j]])

### 1.5.7 奇异值分解

In [23]:
m3

array([[8, 7, 9],
       [7, 9, 0],
       [1, 9, 6]])

In [24]:
U, S_diag, V = linalg.svd(m3)
U

array([[-0.68837303, -0.40911877,  0.59896945],
       [-0.5158753 ,  0.85662848, -0.00776643],
       [-0.5099169 , -0.31433975, -0.80073421]])

In [25]:
S_diag

array([ 19.38490805,   6.39335425,   5.03491421])

$\Sigma$

In [26]:
S = np.zeros((3, 3))
S[np.diag_indices(3)] = S_diag
S

array([[ 19.38490805,   0.        ,   0.        ],
       [  0.        ,   6.39335425,   0.        ],
       [  0.        ,   0.        ,   5.03491421]])

In [27]:
V

array([[-0.4966765 , -0.72482887, -0.47742598],
       [ 0.37681463,  0.31544743, -0.87092115],
       [ 0.78187159, -0.61246716,  0.1164508 ]])

$U.\Sigma.v = m4$

In [28]:
U.dot(S).dot(V) # U.Σ.V == m4

array([[  8.00000000e+00,   7.00000000e+00,   9.00000000e+00],
       [  7.00000000e+00,   9.00000000e+00,   6.34908792e-16],
       [  1.00000000e+00,   9.00000000e+00,   6.00000000e+00]])

### 1.5.8矩阵的主对角线和迹

In [29]:
m3

array([[8, 7, 9],
       [7, 9, 0],
       [1, 9, 6]])

In [30]:
np.diag(m3)

array([8, 9, 6])

In [31]:
np.trace(m3)

23

### 1.5.9 例题分析

给定$m×n$阶矩阵X，满足X = [x1, x2, ... xn]，这里第i列向量是m维向量。   
求$n×n$矩阵，使得$D_{ij} = ||x_i - x_j||^2$

In [32]:
import time

X = np.array([range(0, 500), range(500, 1000)])
m, n = X.shape

t = time.time()
D = np.zeros([n, n])
for i in xrange(n):
    for j in xrange(i + 1, n):
        D[i, j] = linalg.norm(X[:, i] - X[:, j]) ** 2
        D[j, i] = D[i, j]
print time.time() - t

t = time.time()
D = np.zeros([n, n])
for i in xrange(n):
    for j in xrange(i + 1, n):
        d = X[:, i] - X[:, j]
        D[i, j] = np.dot(d, d)
        D[j, i] = D[i, j]
print time.time() - t

t = time.time()
G = np.dot(X.T, X)
D = np.zeros([n, n])
for i in xrange(n):
    for j in xrange(i + 1, n):
        D[i, j] = G[i, i] - G[i, j] * 2 + G[j,j]
        D[j, i] = D[i, j]
print time.time() - t

t = time.time()
G = np.dot(X.T, X)
H = np.tile(np.diag(G), (n, 1))
D = H + H.T - G * 2
print time.time() - t

1.28907299042
0.579629898071
0.279727935791
0.00726103782654
