# Numpy笔记(二)
## 1.3 numpy数组的操作
## 1.3.1 索引

In [1]:
import numpy as np
from numpy import random

操作对象是一维numpy数组时, 索引和python中的列表的索引类似

In [2]:
# 向量的第二个元素
vec = np.array([1,2,3])
vec[1]

2

In [3]:
mtrx = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mtrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


当操作对象是二维numpy数组时, 需要提供行索引和列索引.

In [4]:
# 矩阵第二行第三列的元素
mtrx[1,2]

6

若只提供了行索引, 那么其将返回整行元素.

In [5]:
# 矩阵第二行所有元素
mtrx[1,]

array([4, 5, 6])

若想要返回整列元素, 则需要使用冒号. 

In [6]:
# 不可以直接省略行索引, 以下报错
mtrx[, 2]

SyntaxError: invalid syntax (<ipython-input-6-8366d833bf9d>, line 2)

In [7]:
# 想要返回整列元素, 则需要使用":"来填充行索引
# 矩阵第三列所有元素
mtrx[:, 2]

array([3, 6, 9])

In [8]:
# 刚才返回第二行所有元素我们是这样写的
mtrx[1,]

array([4, 5, 6])

In [9]:
# 完整写法为
mtrx[1,:]

array([4, 5, 6])

### 1.3.2 赋值

In [10]:
vec

array([1, 2, 3])

In [11]:
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# 一维numpy数组的赋值
vec[1] = 9
vec

array([1, 9, 3])

In [13]:
# 二维numpy数组的赋值
mtrx[1,1] = 99
mtrx

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [14]:
# 对整行赋值
mtrx[1,:] = [100, 101, 102]
mtrx

array([[  1,   2,   3],
       [100, 101, 102],
       [  7,   8,   9]])

In [15]:
# 对整列赋值
mtrx[:, 2] = [200, 201, 202]
mtrx

array([[  1,   2, 200],
       [100, 101, 201],
       [  7,   8, 202]])

In [16]:
# 可以将一行或一列的所有元素同时赋值为同一值
mtrx[1,:] = 99
mtrx

array([[  1,   2, 200],
       [ 99,  99,  99],
       [  7,   8, 202]])

### 1.3.3 切片

In [17]:
vec = np.array([1,2,3,4,5])

In [18]:
# 不包含索引'3'
vec[0:3]

array([1, 2, 3])

In [19]:
# ':'左边默认值为0
vec[:3]

array([1, 2, 3])

In [20]:
# ':'右边默认值为元素个数
vec[1:]

array([2, 3, 4, 5])

In [21]:
# 输出索引为0, 2, 4的元素
vec[0:5:2]

array([1, 3, 5])

In [22]:
# 第三个参数默认为1
vec[0:5:]

array([1, 2, 3, 4, 5])

In [23]:
# 最后一个元素, 负号表示倒数
vec[-1]

5

In [24]:
# 倒数第三个元素 - 倒数第一个元素
vec[-3:-1]

array([3, 4])

In [25]:
# 输出索引为: 4, 3, 2, 1, 0
vec[4::-1]

array([5, 4, 3, 2, 1])

In [26]:
# 输出元素为: 倒数第1个, 倒数第2个, 倒数第3个, 倒数第4个, 倒数第5个
vec[-1:-6:-1]

array([5, 4, 3, 2, 1])

In [27]:
# 可以直接省略前两个参数
vec[::-1]

array([5, 4, 3, 2, 1])

以上三种写法都可以表示一个一维numpy数组的逆序

对于二维的numpy数组, 原理是一样的.

In [28]:
mtrx = np.array([[1,2,3,4,5], [3,4,5,6,7], [5,6,7,8,9], [6,7,8,9,10], [7,8,9,10,11]])
mtrx

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

In [29]:
# 第一行到第三行, 第二列到第四列
mtrx[1:4,2:5]

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [30]:
mtrx[::2, ::2]

array([[ 1,  3,  5],
       [ 5,  7,  9],
       [ 7,  9, 11]])

### 1.3.4 遍历数组元素
一般来说, 我们应尽量避免使用循环来遍历numpy数组, 因为它相对于向量化的计算来说效率很低.

In [31]:
# 遍历一维numpu数组
vec = np.array([1,2,3,4,5])
for e in vec:
    print(e)

1
2
3
4
5


In [32]:
# 遍历二维numpu数组
mtrx = np.array([[1,2,3], [4,5,6], [7,8,9]])
for row in mtrx:
    print("row", row)
    for e in row:
        print(e)

row [1 2 3]
1
2
3
row [4 5 6]
4
5
6
row [7 8 9]
7
8
9


In [33]:
# 可以使用enumerate来获取索引
for i, row in enumerate(mtrx):
    print("第" + str(i) + "行:", row)
    for j, e in enumerate(row):
        print("第" + str(i) + "行" + str(j) + "列的元素:", e)

第0行: [1 2 3]
第0行0列的元素: 1
第0行1列的元素: 2
第0行2列的元素: 3
第1行: [4 5 6]
第1行0列的元素: 4
第1行1列的元素: 5
第1行2列的元素: 6
第2行: [7 8 9]
第2行0列的元素: 7
第2行1列的元素: 8
第2行2列的元素: 9


### 1.3.5 改变数组的shape
#### 直接修改shape属性

In [34]:
m = np.arange(12)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
# 维度为 1
print("Rank:", m.ndim)

Rank: 1


In [36]:
# 维度为 2
m.shape = (3, 4)
print(m)
print("Rank:", m.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Rank: 2


In [37]:
# 维度为 3
m.shape = (2, 3, 2)
print(m)
print("Rank:", m.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Rank: 3


#### 使用numpy.reshape()

In [38]:
# 使用reshape创建新的shape为(d1*d2*d3,)的一维数组
d1, d2, d3 = m.shape
n = m.reshape(d1*d2*d3,)
print(n)
print("Rank:", n.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Rank: 1


In [39]:
# reshape不会改变原来的数组
print(m)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [40]:
# 或者可以直接使用flatten函数来得到一个一维数组
a = m.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
# 改变a中某个元素的值
a[10] = 999
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 999,  11])

In [42]:
# 原来数组中的元素并不会改变
m

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [43]:
# 使用ravel函数也可以得到一个一维数组
b = m.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
# 只不过这个时候改变b中某个元素的值, 原来数组中相应元素也会变化
b[10] = 999
print(m)

[[[  0   1]
  [  2   3]
  [  4   5]]

 [[  6   7]
  [  8   9]
  [999  11]]]


### 1.3.6 numpy数组的合并

如下3个numpy数组:

In [45]:
a = np.full((2,3), 1, dtype=int)
b = np.full((3,3), 2, dtype=int)
c = np.full((3,2), 3, dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


In [46]:
print(b)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [47]:
print(c)

[[3 3]
 [3 3]
 [3 3]]


#### vstack
两个数组垂直地合并使用vstack.

In [48]:
print(np.vstack((a, b)))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


#### hstack
两个数组水平地合并使用hstack

In [49]:
print(np.hstack((b, c)))

[[2 2 2 3 3]
 [2 2 2 3 3]
 [2 2 2 3 3]]


#### concatenate

In [50]:
# 相当于vstack
print(np.concatenate((a, b), axis=0))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [51]:
# 相当于hstack
print(np.concatenate((b, c), axis=1))

[[2 2 2 3 3]
 [2 2 2 3 3]
 [2 2 2 3 3]]


#### stack

In [52]:
d = np.full((3,3), 5, dtype=int)
print(d)
print("shape:", d.shape)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
shape: (3, 3)


In [53]:
# stack中的数组必须是同一维度, 合并后会增加维度
e = np.stack((b,d))
print(e)
print("shape:", e.shape)

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]
shape: (2, 3, 3)


### 1.3.7 numpy数组的拆分

In [54]:
mtrx = random.randint(9, size=(3,2))
mtrx

array([[1, 0],
       [1, 2],
       [4, 1]])

In [55]:
a, b, c = np.vsplit(mtrx, 3)

In [56]:
a

array([[1, 0]])

In [57]:
b

array([[1, 2]])

In [58]:
c

array([[4, 1]])

In [59]:
d, e = np.hsplit(mtrx, 2)

In [60]:
d

array([[1],
       [1],
       [4]])

In [61]:
e

array([[0],
       [2],
       [1]])

### 1.3.8 numpy数组的复制

In [62]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
# 传递的是引用, 此时a,b都是这个数组的引用
b = a
b

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
# 此时更改b的值, a也会随之变化
b[1][2] = 10
print(b)

[[ 0  1  2]
 [ 3  4 10]]


In [65]:
print(a)

[[ 0  1  2]
 [ 3  4 10]]


### 1.3.8 numpy数组的条件过滤

In [66]:
mtrx = random.rand(3,3)
mtrx

array([[ 0.29472553,  0.02842487,  0.02559002],
       [ 0.17059967,  0.57710268,  0.38149391],
       [ 0.09233919,  0.69193379,  0.83347123]])

In [67]:
mtrx > 0.5

array([[False, False, False],
       [False,  True, False],
       [False,  True,  True]], dtype=bool)

In [68]:
print(mtrx[mtrx > 0.5])

[ 0.57710268  0.69193379  0.83347123]
