# Numpy笔记(三)
## 1.4 数学运算

### 1.4.1 简单的算术操作
这里的运算是numpy数组对应元素之间的运算, 所以被操作的两个数组的维度是相同的.

In [1]:
import numpy as np
from numpy import random

In [2]:
a = random.randint(10, size=5)
a

array([3, 7, 8, 3, 3])

In [3]:
b = random.randint(5, size=5) + 1
b

array([2, 2, 4, 4, 3])

In [4]:
# 加
print(a + b)

[ 5  9 12  7  6]


In [5]:
# 减
print(a - b)

[ 1  5  4 -1  0]


In [6]:
# 乘
print(a * b)

[ 6 14 32 12  9]


In [7]:
# 除
print(a / b)

[1 3 2 0 1]


In [8]:
# 取余
print(a % b)

[1 1 0 3 0]


In [9]:
# 次幂
print(a ** b)

[   9   49 4096   81   27]


### 1.4.2 Broadcasting

在1.4中我们做运算时, 两个数组的维度是相同的. 若两个数组的维度不同, 那么numpy会调整它们的维度直至一致后再进行运算.

In [10]:
# 例1
a = np.full((1,3), 1, dtype=int)
a

array([[1, 1, 1]])

In [11]:
b = np.full((3,), 2, dtype=int)
b

array([2, 2, 2])

In [12]:
# [[1,1,1]] + [2,2,2]
a + b
# 相当于: [[1,1,1]] + [[2,2,2]]

array([[3, 3, 3]])

In [13]:
# 例2
c = np.arange(6).reshape(2, 3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
d = np.arange(2).reshape(2,1)
d

array([[0],
       [1]])

In [15]:
# [[0,1,2],[3,4,5]] + [[0],[1]]
c + d
# 相当于: [[0,1,2],[3,4,5]] + [[0,0,0],[1,1,1]]

array([[0, 1, 2],
       [4, 5, 6]])

In [16]:
# 例3
f = np.arange(3).reshape(1,3)
f

array([[0, 1, 2]])

In [17]:
# [[0,1,2],[3,4,5]] + [[0,1,2]]
c + f
# 相当于: [[0,1,2],[3,4,5]] + [[0,1,2],[0,1,2]]

array([[0, 2, 4],
       [3, 5, 7]])

In [18]:
# 例4
g = np.array([1])
g

array([1])

In [19]:
# [[0,1,2],[3,4,5]] + [1]
c + g
# 相当于: [[0,1,2],[3,4,5]] + [[1,1,1],[1,1,1]]

array([[1, 2, 3],
       [4, 5, 6]])

更多关于Broadcasting请参考[Numpy官方文档](https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html).

### 1.4.3 数理统计

In [20]:
a = random.randint(10, size=(3,2))
print(a)

[[1 7]
 [2 0]
 [3 8]]


#### 最小值和最大值

In [21]:
print(a.min())

0


In [22]:
print(a.max())

8


#### 求和

In [23]:
a.sum()

21

#### 累积

In [24]:
a.prod()

0

#### 均值

In [25]:
a.mean()

3.5

#### 方差

In [26]:
a.var()

8.9166666666666661

#### 标准差

In [27]:
a.std()

2.9860788111948193

以上所有结果都是按照所有元素来进行计算的, 我们可以使用参数来按列或行进行计算. 以均值为例:

In [28]:
# 按照列计算均值
a.mean(axis=0)

array([ 2.,  5.])

In [29]:
# 按照行计算均值
a.mean(axis=1)

array([ 4. ,  1. ,  5.5])

### 1.4.4 Universal functions

In [30]:
a

array([[1, 7],
       [2, 0],
       [3, 8]])

In [31]:
np.square(a)

array([[ 1, 49],
       [ 4,  0],
       [ 9, 64]])

In [32]:
np.abs(a)

array([[1, 7],
       [2, 0],
       [3, 8]])

In [33]:
np.sqrt(a)

array([[ 1.        ,  2.64575131],
       [ 1.41421356,  0.        ],
       [ 1.73205081,  2.82842712]])

In [34]:
np.exp(a)

array([[  2.71828183e+00,   1.09663316e+03],
       [  7.38905610e+00,   1.00000000e+00],
       [  2.00855369e+01,   2.98095799e+03]])

In [35]:
np.log(a)

/Users/bobo/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([[ 0.        ,  1.94591015],
       [ 0.69314718,        -inf],
       [ 1.09861229,  2.07944154]])

In [36]:
np.sin(a)

array([[ 0.84147098,  0.6569866 ],
       [ 0.90929743,  0.        ],
       [ 0.14112001,  0.98935825]])

In [37]:
np.cos(a)

array([[ 0.54030231,  0.75390225],
       [-0.41614684,  1.        ],
       [-0.9899925 , -0.14550003]])

In [38]:
b = random.randint(10, size=(3,2))
b

array([[2, 8],
       [2, 9],
       [2, 5]])

In [39]:
# 相当于 a + b
np.add(a, b)

array([[ 3, 15],
       [ 4,  9],
       [ 5, 13]])

In [40]:
# 相当于 a > b
np.greater(a, b)  # equivalent to a > b

array([[False, False],
       [False, False],
       [ True,  True]], dtype=bool)

In [41]:
np.maximum(a, b)

array([[2, 8],
       [2, 9],
       [3, 8]])

更多关于ufunc, 请参考[Numpy官方文档](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)