# Numpy笔记(四)
## 1.5 线性代数
### 1.5.1 矩阵的转置
使用**T**属性来获取某一矩阵的转置

In [1]:
import numpy as np
from numpy import random

In [2]:
matrix = random.randint(10, size=(3,2))
matrix

array([[4, 3],
       [8, 7],
       [0, 8]])

In [3]:
matrix.T

array([[4, 8, 0],
       [3, 7, 8]])

### 1.5.2 矩阵的乘法

In [4]:
m1 = random.randint(10, size=(3,2))
m1

array([[4, 9],
       [9, 2],
       [0, 5]])

In [5]:
m2 = random.randint(10, size=(2,3))
m2

array([[3, 6, 1],
       [9, 3, 0]])

In [6]:
m1.dot(m2)

array([[93, 51,  4],
       [45, 60,  9],
       [45, 15,  0]])

### 1.5.3 矩阵的逆
首先导入**numpy.linalg**.

In [7]:
import numpy.linalg as linalg

In [8]:
m3 = random.randint(10, size=(3,3))
m3

array([[2, 3, 9],
       [4, 2, 3],
       [9, 5, 6]])

In [9]:
linalg.inv(m3)

array([[-0.14285714,  1.28571429, -0.42857143],
       [ 0.14285714, -3.28571429,  1.42857143],
       [ 0.0952381 ,  0.80952381, -0.38095238]])

### 1.5.4 QR分解

In [10]:
m3

array([[2, 3, 9],
       [4, 2, 3],
       [9, 5, 6]])

In [11]:
q, r = linalg.qr(m3)
q

array([[-0.19900744,  0.97426462, -0.10585122],
       [-0.39801488, -0.17905404, -0.89973541],
       [-0.89553347, -0.13692368,  0.4234049 ]])

In [12]:
r

array([[-10.04987562,  -5.87071942,  -8.3583124 ],
       [  0.        ,   1.88006741,   7.40967744],
       [  0.        ,   0.        ,  -1.11143786]])

In [13]:
q.dot(r)

array([[ 2.,  3.,  9.],
       [ 4.,  2.,  3.],
       [ 9.,  5.,  6.]])

### 1.5.5 矩阵的秩

In [14]:
linalg.det(m3)

21.0

### 1.5.6 特征值和特征向量

In [15]:
eigenvalues, eigenvectors = linalg.eig(m3)

In [16]:
eigenvalues

array([ 15.31364755,  -5.04164804,  -0.27199951])

In [17]:
eigenvectors

array([[ 0.57801818,  0.80254166,  0.35678932],
       [ 0.34074121, -0.21954738, -0.90955136],
       [ 0.74147853, -0.55473042,  0.21311432]])

$ Av=\lambda v,  Av- \lambda v=0$

In [18]:
m3.dot(eigenvectors) - eigenvalues * eigenvectors  

array([[  5.32907052e-15,   0.00000000e+00,   3.19189120e-16],
       [  8.88178420e-16,   4.44089210e-16,   6.93889390e-16],
       [  5.32907052e-15,  -1.33226763e-15,   9.64506253e-16]])

### 1.5.7 奇异值分解

In [19]:
m3

array([[2, 3, 9],
       [4, 2, 3],
       [9, 5, 6]])

In [20]:
U, S_diag, V = linalg.svd(m3)
U

array([[-0.56075559,  0.82700907,  0.0401143 ],
       [-0.34393245, -0.18858612, -0.91986181],
       [-0.75316906, -0.52961427,  0.39018598]])

In [21]:
S_diag

array([ 15.36227084,   5.37922448,   0.25412314])

$\Sigma$

In [22]:
S = np.zeros((3, 3))
S[np.diag_indices(3)] = S_diag
S

array([[ 15.36227084,   0.        ,   0.        ],
       [  0.        ,   5.37922448,   0.        ],
       [  0.        ,   0.        ,   0.25412314]])

In [23]:
V

array([[-0.60380152, -0.39941862, -0.68984671],
       [-0.71884985, -0.10117004,  0.68776414],
       [-0.34449762,  0.91116924, -0.22603539]])

$U.\Sigma.v = m4$

In [24]:
U.dot(S).dot(V) # U.Σ.V == m4

array([[ 2.,  3.,  9.],
       [ 4.,  2.,  3.],
       [ 9.,  5.,  6.]])

### 1.5.8矩阵的主对角线和迹

In [25]:
m3

array([[2, 3, 9],
       [4, 2, 3],
       [9, 5, 6]])

In [26]:
np.diag(m3)

array([2, 2, 6])

In [27]:
np.trace(m3)

10